# See   https://github.com/kubernetes-sigs/kind/blob/master/pkg/apis/config/v1alpha4/types.go
#       https://kind.sigs.k8s.io/docs/user/configuration/#kubeadm-config-patches
#       https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/control-plane-flags/
#       https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/apis/kubeadm/v1beta2/types.go
#       https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

apiVersion: kind.x-k8s.io/v1alpha4

featureGates:
  EphemeralContainers: true               # See https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

kind: Cluster

nodes:
- role: control-plane
- role: worker
