apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "ktsg-argocd-demo.labels" . | nindent 4 }}
  name: {{ include "ktsg-argocd-demo.fullname" . }}
spec:
  ports:
  - name: http
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: http
  selector:
    {{- include "ktsg-argocd-demo.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
