# Defaults

affinity: {}

autoscaling:
  enabled: true
  maxReplicas: 5
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

fullnameOverride: ""

image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/pmcgrath/ktsg-argocd-demo
  tag: ""                                               # Overrides the image tag whose default is the chart appVersion.

imagePullSecrets: []

ingress:
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  enabled: true
  hosts:
  - host: ktsg-argocd-demo.local
    paths:
    - path: /
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

nameOverride: ""

nodeSelector: {}

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

replicaCount: 1

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 20m
    memory: 75Mi
  requests:
    cpu: 20m
    memory: 75Mi

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsGroup: 65534 
  runAsNonRoot: true
  runAsUser: 65534

service:
  type: ClusterIP
  port: 80

serviceAccount:
  annotations: {}                                       # Annotations to add to the service account
  create: true                                          # Specifies whether a service account should be created
  name: ""                                              # The name of the service account to use, if not set and create is true, a name is generated using the fullname template

tolerations: []
